export const COLOR = {
  BLACK: "#3D3429",
  LIGHT_BROWN: "#EEE7DF",
  EXTRA_LIGHT_BROWN: "#FBF9F7",
  EXTRA_LIGHT_BROWN_2: "#E4DED7",
  BROWN: "#907B62",
  LIGHT_GRAY: "#f7f5f3",
  WHITE: "#ffffff",
};
